spring:
  jpa:
    generate-ddl: true
  application:
    name: spring-music

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 0.5
  wavefront:
    application:
      name: MY-APPLICATION
      service-name: MY-SERVICE
      custom-tags:
        instance_guid: ${CF_INSTANCE_GUID}
    api-token: 1111-23this-45is-678a-faketoken
    uri: http://telegraf.hub-collector.service.internal:8765
  server:
    port: 8080

---
spring:
  config:
    activate:
      on-profile: http2

server:
  http2:
    enabled: true

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: "jdbc:mysql://localhost/music"
    driver-class-name: com.mysql.jdbc.Driver
    username:
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect

---
spring:
  config:
    activate:
      on-profile: postgres
  datasource:
    url: "jdbc:postgresql://localhost/music"
    driver-class-name: org.postgresql.Driver
    username: postgres
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.ProgressDialect
